Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -59,36 +59,37 @@ jobs:
           echo "Deploying to Q/A environment"
 
   deploy-prod:
-    needs: deploy-qa
-    runs-on: ubuntu-latest
-    environment: production
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+   needs: deploy-qa
+   runs-on: ubuntu-latest
+   environment: production
+   steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
 
-      - name: Check for .cpanel.yml
-        run: |
-          if [ ! -f .cpanel.yml ]; then
-            echo ".cpanel.yml file not found. Deployment cannot proceed."
-            exit 1
-          fi
+    - name: Check for .cpanel.yml
+      run: |
+        if [ ! -f .cpanel.yml ]; then
+          echo ".cpanel.yml file not found. Deployment cannot proceed."
+          exit 1
+        fi
 
-      - name: Check for uncommitted changes
-        run: |
-          if [ -n "$(git status --porcelain)" ]; then
-            echo "There are uncommitted changes. Deployment cannot proceed."
-            exit 1
-          fi
+    - name: Check for uncommitted changes
+      run: |
+        if [ -n "$(git status --porcelain)" ]; then
+          echo "There are uncommitted changes. Deployment cannot proceed."
+          exit 1
+        fi
 
-      - name: Deploy to Production (Docker)
-        run: |
-          docker run -d -p 8082:80 --name prod_container design399/crm_docker:latest
-          echo "Deploying to Production environment"
-      
-      - name: Deploy to Production (cPanel)
-        uses: SamKirkland/FTP-Deploy-Action@4.3.3
-        with:
-          server: ${{ secrets.FTP_SERVER }}
-          username: ${{ secrets.FTP_USERNAME }}
-          password: ${{ secrets.FTP_PASSWORD }}
-          server-dir: ${{ secrets.FTP_SERVER_DIR }}/
+    - name: Deploy to Production (Docker)
+      run: |
+        docker run -d -p 8082:80 --name prod_container design399/crm_docker:latest
+        echo "Deploying to Production environment"
+    
+    - name: Deploy to Production (cPanel)
+      uses: SamKirkland/FTP-Deploy-Action@4.3.3
+      with:
+        server: ${{ secrets.FTP_SERVER }}
+        username: ${{ secrets.FTP_USERNAME }}
+        password: ${{ secrets.FTP_PASSWORD }}
+        server-dir: ${{ secrets.FTP_SERVER_DIR }}/
+
